# coding: utf-8

"""
    characters

    Your custom SDK

    The version of the OpenAPI document: characters: v3 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class StorageBlobAndOwner(BaseModel):
    """
    StorageBlobAndOwner
    """
    access_type: Optional[StrictStr] = None
    cas: Optional[StrictStr] = None
    key: Optional[StrictStr] = None
    owner_id: Optional[StrictStr] = None
    scope: Optional[StrictStr] = None
    value: Optional[StrictStr] = None
    __properties = ["access_type", "cas", "key", "owner_id", "scope", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StorageBlobAndOwner:
        """Create an instance of StorageBlobAndOwner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StorageBlobAndOwner:
        """Create an instance of StorageBlobAndOwner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StorageBlobAndOwner.parse_obj(obj)

        _obj = StorageBlobAndOwner.parse_obj({
            "access_type": obj.get("access_type"),
            "cas": obj.get("cas"),
            "key": obj.get("key"),
            "owner_id": obj.get("owner_id"),
            "scope": obj.get("scope"),
            "value": obj.get("value")
        })
        return _obj


