# coding: utf-8

"""
    game-dev

    Your custom SDK

    The version of the OpenAPI document: game-dev: v2 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from snapser_internal.models.storage_upsert_sub_document_request import StorageUpsertSubDocumentRequest

class StorageBatchUpsertSubDocumentsRequest(BaseModel):
    """
    StorageBatchUpsertSubDocumentsRequest
    """
    sub_documents: Optional[conlist(StorageUpsertSubDocumentRequest)] = None
    __properties = ["sub_documents"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StorageBatchUpsertSubDocumentsRequest:
        """Create an instance of StorageBatchUpsertSubDocumentsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in sub_documents (list)
        _items = []
        if self.sub_documents:
            for _item in self.sub_documents:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sub_documents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StorageBatchUpsertSubDocumentsRequest:
        """Create an instance of StorageBatchUpsertSubDocumentsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StorageBatchUpsertSubDocumentsRequest.parse_obj(obj)

        _obj = StorageBatchUpsertSubDocumentsRequest.parse_obj({
            "sub_documents": [StorageUpsertSubDocumentRequest.from_dict(_item) for _item in obj.get("sub_documents")] if obj.get("sub_documents") is not None else None
        })
        return _obj


