/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorResponseSchemaId } from './errorResponseSchemaId';

export class ErrorResponseSchema {
    /**
    * JSON-RPC error object (code, message, optional data).
    */
    'error': object;
    'id'?: ErrorResponseSchemaId | null;
    /**
    * JSON-RPC version, always \'2.0\'.
    */
    'jsonrpc': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "object"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "ErrorResponseSchemaId"
        },
        {
            "name": "jsonrpc",
            "baseName": "jsonrpc",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ErrorResponseSchema.attributeTypeMap;
    }
}

