/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageBlobAndOwner } from './storageBlobAndOwner';
import { StorageReplaceBlobRequest } from './storageReplaceBlobRequest';

export class StorageBatchSingleReplaceBlobResponse {
    'message'?: string;
    'request'?: StorageReplaceBlobRequest;
    'response'?: StorageBlobAndOwner;
    'success'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "StorageReplaceBlobRequest"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "StorageBlobAndOwner"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StorageBatchSingleReplaceBlobResponse.attributeTypeMap;
    }
}

