/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageGetAppendBlobRequest } from './storageGetAppendBlobRequest';
import { StorageUserAppendBlobResponse } from './storageUserAppendBlobResponse';

export class StorageBatchGetAppendBlobsSingleResponse {
    'message'?: string;
    'request'?: StorageGetAppendBlobRequest;
    'response'?: StorageUserAppendBlobResponse;
    'success'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "StorageGetAppendBlobRequest"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "StorageUserAppendBlobResponse"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StorageBatchGetAppendBlobsSingleResponse.attributeTypeMap;
    }
}

