/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StorageInsertBlobRequest {
    /**
    * Access to the blob. (public/protected/private)
    */
    'accessType': StorageInsertBlobRequest.AccessTypeEnum;
    /**
    * Blob key
    */
    'blobKey': string;
    /**
    * Blob owner\'s user ID
    */
    'ownerId': string;
    /**
    * Optional TTL for the blob
    */
    'ttl'?: number;
    /**
    * Blob value to be inserted
    */
    'value': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessType",
            "baseName": "access_type",
            "type": "StorageInsertBlobRequest.AccessTypeEnum"
        },
        {
            "name": "blobKey",
            "baseName": "blob_key",
            "type": "string"
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "string"
        },
        {
            "name": "ttl",
            "baseName": "ttl",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StorageInsertBlobRequest.attributeTypeMap;
    }
}

export namespace StorageInsertBlobRequest {
    export enum AccessTypeEnum {
        Public = <any> 'public',
        Private = <any> 'private',
        Protected = <any> 'protected'
    }
}
