/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageBatchGetCountersSingleResponse } from './storageBatchGetCountersSingleResponse';
import { StorageUserCounterResponse } from './storageUserCounterResponse';

export class StorageBatchGetCountersResponse {
    'counters'?: Array<StorageUserCounterResponse>;
    'results'?: Array<StorageBatchGetCountersSingleResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "counters",
            "baseName": "counters",
            "type": "Array<StorageUserCounterResponse>"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<StorageBatchGetCountersSingleResponse>"
        }    ];

    static getAttributeTypeMap() {
        return StorageBatchGetCountersResponse.attributeTypeMap;
    }
}

