/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageBatchInsertJsonBlobSingleResponse } from './storageBatchInsertJsonBlobSingleResponse';

export class StorageBatchInsertJsonBlobsResponse {
    'results'?: Array<StorageBatchInsertJsonBlobSingleResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<StorageBatchInsertJsonBlobSingleResponse>"
        }    ];

    static getAttributeTypeMap() {
        return StorageBatchInsertJsonBlobsResponse.attributeTypeMap;
    }
}

