/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StorageGetJsonBlobRequest {
    /**
    * Access to the blob. (public/protected/private)
    */
    'accessType': StorageGetJsonBlobRequest.AccessTypeEnum;
    /**
    * Blob key
    */
    'jsonBlobKey': string;
    /**
    * Blob owner\'s user ID
    */
    'ownerId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessType",
            "baseName": "access_type",
            "type": "StorageGetJsonBlobRequest.AccessTypeEnum"
        },
        {
            "name": "jsonBlobKey",
            "baseName": "json_blob_key",
            "type": "string"
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StorageGetJsonBlobRequest.attributeTypeMap;
    }
}

export namespace StorageGetJsonBlobRequest {
    export enum AccessTypeEnum {
        Public = <any> 'public',
        Private = <any> 'private',
        Protected = <any> 'protected'
    }
}
