/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StorageBlobAndOwner {
    'accessType'?: string;
    'cas'?: string;
    'key'?: string;
    'ownerId'?: string;
    'scope'?: string;
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessType",
            "baseName": "access_type",
            "type": "string"
        },
        {
            "name": "cas",
            "baseName": "cas",
            "type": "string"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "string"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StorageBlobAndOwner.attributeTypeMap;
    }
}

