/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageBatchGetAppendBlobsSingleResponse } from './storageBatchGetAppendBlobsSingleResponse';
import { StorageUserAppendBlobResponse } from './storageUserAppendBlobResponse';

export class StorageBatchGetAppendBlobsResponse {
    'appendBlobs'?: Array<StorageUserAppendBlobResponse>;
    'results'?: Array<StorageBatchGetAppendBlobsSingleResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appendBlobs",
            "baseName": "append_blobs",
            "type": "Array<StorageUserAppendBlobResponse>"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<StorageBatchGetAppendBlobsSingleResponse>"
        }    ];

    static getAttributeTypeMap() {
        return StorageBatchGetAppendBlobsResponse.attributeTypeMap;
    }
}

