/**
 * dev-one
 * Your custom SDK
 *
 * The version of the OpenAPI document: dev-one: v7 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StorageAppendBlobAndOwner } from './storageAppendBlobAndOwner';
import { StorageUpdateAppendBlobRequest } from './storageUpdateAppendBlobRequest';

export class StorageBatchSingleUpdateAppendBlobResponse {
    'message'?: string;
    'request'?: StorageUpdateAppendBlobRequest;
    'response'?: StorageAppendBlobAndOwner;
    'success'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "StorageUpdateAppendBlobRequest"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "StorageAppendBlobAndOwner"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StorageBatchSingleUpdateAppendBlobResponse.attributeTypeMap;
    }
}

