import express, { Application } from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import { RegisterRoutes } from './routes'; // This will be generated by TSOA
import { requestIdMiddleware } from './logger';

export const app: Application = express();
app.use(cors());
app.use(bodyParser.json());
// Must run before the routes so every log line in a request carries its
// X-Request-Id. Snapser uses it to correlate logs across snaps.
app.use(requestIdMiddleware);

RegisterRoutes(app);

app.get('/healthz', (req, res) => { res.send('OK'); });

// Handle undefined routes
app.use((req, res) => {
    res.status(404).send({ message: 'Not Found' });
});
