/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v9 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthVerifyEmailRequest {
    /**
    * Email address to verify
    */
    'email': string;
    /**
    * Verification code received by the user
    */
    'verificationCode': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "verificationCode",
            "baseName": "verification_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AuthVerifyEmailRequest.attributeTypeMap;
    }
}

