/**
 * juhi-dev
 * Your custom SDK
 *
 * The version of the OpenAPI document: juhi-dev: v4 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AuthLoginId } from './authLoginId';
import { AuthLoginTypeType } from './authLoginTypeType';

export class AuthUser {
    /**
    * Whether user was created or not
    */
    'created'?: boolean;
    /**
    * Unix timestamp of when the user was created
    */
    'createdAt'?: number;
    /**
    * Unix timestamp of when the user was first logged in
    */
    'firstLogin'?: number;
    /**
    * User ID for the user
    */
    'id'?: string;
    /**
    * Whether user is banned or not
    */
    'isBanned'?: boolean;
    /**
    * Whether user is suspended or not
    */
    'isSuspended'?: boolean;
    /**
    * Whether user is verified or not
    */
    'isVerified'?: boolean;
    /**
    * Login types
    */
    'loginTypes'?: Array<AuthLoginTypeType>;
    /**
    * List of login IDs associated with the user
    */
    'logins'?: Array<AuthLoginId>;
    /**
    * Unix timestamp of when the session was last refreshed (If applicable)
    */
    'refreshedAt'?: number;
    /**
    * Session token of the user (If applicable)
    */
    'sessionToken'?: string;
    /**
    * Unix timestamp of when the user is suspended until
    */
    'suspendedUntil'?: number;
    /**
    * Different tags attached to the user like flagged
    */
    'tags'?: Array<string>;
    /**
    * Validity of the token in seconds (If applicable)
    */
    'tokenValiditySeconds'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number"
        },
        {
            "name": "firstLogin",
            "baseName": "first_login",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isBanned",
            "baseName": "is_banned",
            "type": "boolean"
        },
        {
            "name": "isSuspended",
            "baseName": "is_suspended",
            "type": "boolean"
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean"
        },
        {
            "name": "loginTypes",
            "baseName": "login_types",
            "type": "Array<AuthLoginTypeType>"
        },
        {
            "name": "logins",
            "baseName": "logins",
            "type": "Array<AuthLoginId>"
        },
        {
            "name": "refreshedAt",
            "baseName": "refreshed_at",
            "type": "number"
        },
        {
            "name": "sessionToken",
            "baseName": "session_token",
            "type": "string"
        },
        {
            "name": "suspendedUntil",
            "baseName": "suspended_until",
            "type": "number"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "tokenValiditySeconds",
            "baseName": "token_validity_seconds",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AuthUser.attributeTypeMap;
    }
}

