/**
 * juhi-dev
 * Your custom SDK
 *
 * The version of the OpenAPI document: juhi-dev: v4 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AuthLoginTypeType } from './authLoginTypeType';

export class DisassociateLoginRequest {
    'loginType': AuthLoginTypeType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "loginType",
            "baseName": "login_type",
            "type": "AuthLoginTypeType"
        }    ];

    static getAttributeTypeMap() {
        return DisassociateLoginRequest.attributeTypeMap;
    }
}

export namespace DisassociateLoginRequest {
}
