/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v9 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfilesBatchGetProfilesSingleResponse } from './profilesBatchGetProfilesSingleResponse';

export class ProfilesBatchGetProfilesResponse {
    'profiles'?: { [key: string]: object; };
    /**
    * List of responses for each user ID
    */
    'responses'?: Array<ProfilesBatchGetProfilesSingleResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "responses",
            "baseName": "responses",
            "type": "Array<ProfilesBatchGetProfilesSingleResponse>"
        }    ];

    static getAttributeTypeMap() {
        return ProfilesBatchGetProfilesResponse.attributeTypeMap;
    }
}

