/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProfilesGetProfileRequest } from './profilesGetProfileRequest';

export class ProfilesBatchGetProfilesSingleResponse {
    'message'?: string;
    'request'?: ProfilesGetProfileRequest;
    'response'?: object;
    'success'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "ProfilesGetProfileRequest"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "object"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ProfilesBatchGetProfilesSingleResponse.attributeTypeMap;
    }
}

