# coding: utf-8

"""
    juhi-dev

    Your custom SDK

    The version of the OpenAPI document: juhi-dev: v4 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AuthLoginTypeType(str, Enum):
    """
    AuthLoginTypeType
    """

    """
    allowed enum values
    """
    UNSPECIFIED_LOGIN_TYPE = 'UNSPECIFIED_LOGIN_TYPE'
    EMAIL = 'EMAIL'
    PASSWORD = 'PASSWORD'
    ANON = 'ANON'
    FACEBOOK = 'FACEBOOK'
    GOOGLE = 'GOOGLE'
    APPLE = 'APPLE'
    STEAM = 'STEAM'
    XBOX = 'XBOX'
    EPIC = 'EPIC'
    APP = 'APP'
    DISCORD = 'DISCORD'
    EMAIL_PASSWORD = 'EMAIL_PASSWORD'
    USERNAME_PASSWORD = 'USERNAME_PASSWORD'
    X = 'X'

    @classmethod
    def from_json(cls, json_str: str) -> AuthLoginTypeType:
        """Create an instance of AuthLoginTypeType from a JSON string"""
        return AuthLoginTypeType(json.loads(json_str))


