# coding: utf-8

"""
    my-dev-cluster

    Your custom SDK

    The version of the OpenAPI document: my-dev-cluster: v1 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class AuthOtpRequest(BaseModel):
    """
    AuthOtpRequest
    """
    email: StrictStr = Field(..., description="Email address to send OTP to")
    validate_user_exists: Optional[StrictBool] = Field(None, description="If set to true, OTP won't be sent if user doesn't exist")
    __properties = ["email", "validate_user_exists"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AuthOtpRequest:
        """Create an instance of AuthOtpRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AuthOtpRequest:
        """Create an instance of AuthOtpRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AuthOtpRequest.parse_obj(obj)

        _obj = AuthOtpRequest.parse_obj({
            "email": obj.get("email"),
            "validate_user_exists": obj.get("validate_user_exists")
        })
        return _obj


