# coding: utf-8

"""
    my-dev-cluster

    Your custom SDK

    The version of the OpenAPI document: my-dev-cluster: v1 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from snapser_internal.models.search_field_operator import SearchFieldOperator

class ProfilesSearchField(BaseModel):
    """
    ProfilesSearchField
    """
    key: Optional[StrictStr] = Field(None, description="Key of the field to search by")
    operator: Optional[SearchFieldOperator] = None
    value: Optional[StrictStr] = Field(None, description="Value of the field to search by")
    __properties = ["key", "operator", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProfilesSearchField:
        """Create an instance of ProfilesSearchField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProfilesSearchField:
        """Create an instance of ProfilesSearchField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProfilesSearchField.parse_obj(obj)

        _obj = ProfilesSearchField.parse_obj({
            "key": obj.get("key"),
            "operator": obj.get("operator"),
            "value": obj.get("value")
        })
        return _obj


