# coding: utf-8

"""
    my-dev-cluster

    Your custom SDK

    The version of the OpenAPI document: my-dev-cluster: v9 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class ProfilesGetProfileRequest(BaseModel):
    """
    ProfilesGetProfileRequest
    """
    user_id: StrictStr = Field(..., description="User ID of the user who's profile is being viewed")
    __properties = ["user_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProfilesGetProfileRequest:
        """Create an instance of ProfilesGetProfileRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProfilesGetProfileRequest:
        """Create an instance of ProfilesGetProfileRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProfilesGetProfileRequest.parse_obj(obj)

        _obj = ProfilesGetProfileRequest.parse_obj({
            "user_id": obj.get("user_id")
        })
        return _obj


