# coding: utf-8

"""
    my-dev-cluster

    Your custom SDK

    The version of the OpenAPI document: my-dev-cluster: v9 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SearchFieldOperator(str, Enum):
    """
    SearchFieldOperator
    """

    """
    allowed enum values
    """
    UNSPECIFIED_OPERATOR = 'UNSPECIFIED_OPERATOR'
    EQUALS = 'EQUALS'
    NOT_EQUALS = 'NOT_EQUALS'
    CONTAINS = 'CONTAINS'

    @classmethod
    def from_json(cls, json_str: str) -> SearchFieldOperator:
        """Create an instance of SearchFieldOperator from a JSON string"""
        return SearchFieldOperator(json.loads(json_str))


