# coding: utf-8

"""
    juhi-dev

    Your custom SDK

    The version of the OpenAPI document: juhi-dev: v5 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conint

class ReplaceJsonBlobRequest(BaseModel):
    """
    ReplaceJsonBlobRequest
    """
    cas: Optional[StrictStr] = Field(None, description="CAS value retrieved from the last operation")
    create: Optional[StrictBool] = Field(None, description="Whether the json blob should be created if it doesn't exist")
    ttl: Optional[conint()] = Field(None, description="Optional TTL for the json blob")
    value: Dict[str, Any] = Field(..., description="JSON value to be inserted")
    __properties = ["cas", "create", "ttl", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReplaceJsonBlobRequest:
        """Create an instance of ReplaceJsonBlobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReplaceJsonBlobRequest:
        """Create an instance of ReplaceJsonBlobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ReplaceJsonBlobRequest.parse_obj(obj)

        _obj = ReplaceJsonBlobRequest.parse_obj({
            "cas": obj.get("cas"),
            "create": obj.get("create"),
            "ttl": obj.get("ttl"),
            "value": obj.get("value")
        })
        return _obj


