# coding: utf-8

"""
    juhi-dev

    Your custom SDK

    The version of the OpenAPI document: juhi-dev: v5 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from snapser_internal.models.storage_batch_get_append_blobs_single_response import StorageBatchGetAppendBlobsSingleResponse
from snapser_internal.models.storage_user_append_blob_response import StorageUserAppendBlobResponse

class StorageBatchGetAppendBlobsResponse(BaseModel):
    """
    StorageBatchGetAppendBlobsResponse
    """
    append_blobs: Optional[conlist(StorageUserAppendBlobResponse)] = None
    results: Optional[conlist(StorageBatchGetAppendBlobsSingleResponse)] = None
    __properties = ["append_blobs", "results"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StorageBatchGetAppendBlobsResponse:
        """Create an instance of StorageBatchGetAppendBlobsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in append_blobs (list)
        _items = []
        if self.append_blobs:
            for _item in self.append_blobs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['append_blobs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item in self.results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['results'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StorageBatchGetAppendBlobsResponse:
        """Create an instance of StorageBatchGetAppendBlobsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StorageBatchGetAppendBlobsResponse.parse_obj(obj)

        _obj = StorageBatchGetAppendBlobsResponse.parse_obj({
            "append_blobs": [StorageUserAppendBlobResponse.from_dict(_item) for _item in obj.get("append_blobs")] if obj.get("append_blobs") is not None else None,
            "results": [StorageBatchGetAppendBlobsSingleResponse.from_dict(_item) for _item in obj.get("results")] if obj.get("results") is not None else None
        })
        return _obj


