# coding: utf-8

"""
    my-dev-cluster

    Your custom SDK

    The version of the OpenAPI document: my-dev-cluster: v1 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from snapser_internal.models.storage_json_fragment import StorageJsonFragment

class UpsertSubDocumentRequest(BaseModel):
    """
    UpsertSubDocumentRequest
    """
    updates: conlist(StorageJsonFragment) = Field(..., description="Fragments to be upserted")
    __properties = ["updates"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpsertSubDocumentRequest:
        """Create an instance of UpsertSubDocumentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in updates (list)
        _items = []
        if self.updates:
            for _item in self.updates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['updates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpsertSubDocumentRequest:
        """Create an instance of UpsertSubDocumentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpsertSubDocumentRequest.parse_obj(obj)

        _obj = UpsertSubDocumentRequest.parse_obj({
            "updates": [StorageJsonFragment.from_dict(_item) for _item in obj.get("updates")] if obj.get("updates") is not None else None
        })
        return _obj


