/*
my-dev-cluster

Your custom SDK

API version: my-dev-cluster: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the DisassociateLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisassociateLoginRequest{}

// DisassociateLoginRequest struct for DisassociateLoginRequest
type DisassociateLoginRequest struct {
	// Login type
	LoginType string `json:"login_type"`
}

// NewDisassociateLoginRequest instantiates a new DisassociateLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisassociateLoginRequest(loginType string) *DisassociateLoginRequest {
	this := DisassociateLoginRequest{}
	this.LoginType = loginType
	return &this
}

// NewDisassociateLoginRequestWithDefaults instantiates a new DisassociateLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisassociateLoginRequestWithDefaults() *DisassociateLoginRequest {
	this := DisassociateLoginRequest{}
	return &this
}

// GetLoginType returns the LoginType field value
func (o *DisassociateLoginRequest) GetLoginType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LoginType
}

// GetLoginTypeOk returns a tuple with the LoginType field value
// and a boolean to check if the value has been set.
func (o *DisassociateLoginRequest) GetLoginTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoginType, true
}

// SetLoginType sets field value
func (o *DisassociateLoginRequest) SetLoginType(v string) {
	o.LoginType = v
}

func (o DisassociateLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisassociateLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["login_type"] = o.LoginType
	return toSerialize, nil
}

type NullableDisassociateLoginRequest struct {
	value *DisassociateLoginRequest
	isSet bool
}

func (v NullableDisassociateLoginRequest) Get() *DisassociateLoginRequest {
	return v.value
}

func (v *NullableDisassociateLoginRequest) Set(val *DisassociateLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDisassociateLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDisassociateLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisassociateLoginRequest(val *DisassociateLoginRequest) *NullableDisassociateLoginRequest {
	return &NullableDisassociateLoginRequest{value: val, isSet: true}
}

func (v NullableDisassociateLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisassociateLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


