/*
juhi-dev

Your custom SDK

API version: juhi-dev: v4 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the ProfilesPatchProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfilesPatchProfileResponse{}

// ProfilesPatchProfileResponse struct for ProfilesPatchProfileResponse
type ProfilesPatchProfileResponse struct {
	// JSON representation of the user's profile after the patch
	Profile map[string]interface{} `json:"profile,omitempty"`
}

// NewProfilesPatchProfileResponse instantiates a new ProfilesPatchProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfilesPatchProfileResponse() *ProfilesPatchProfileResponse {
	this := ProfilesPatchProfileResponse{}
	return &this
}

// NewProfilesPatchProfileResponseWithDefaults instantiates a new ProfilesPatchProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfilesPatchProfileResponseWithDefaults() *ProfilesPatchProfileResponse {
	this := ProfilesPatchProfileResponse{}
	return &this
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *ProfilesPatchProfileResponse) GetProfile() map[string]interface{} {
	if o == nil || IsNil(o.Profile) {
		var ret map[string]interface{}
		return ret
	}
	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilesPatchProfileResponse) GetProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Profile) {
		return map[string]interface{}{}, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *ProfilesPatchProfileResponse) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given map[string]interface{} and assigns it to the Profile field.
func (o *ProfilesPatchProfileResponse) SetProfile(v map[string]interface{}) {
	o.Profile = v
}

func (o ProfilesPatchProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfilesPatchProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	return toSerialize, nil
}

type NullableProfilesPatchProfileResponse struct {
	value *ProfilesPatchProfileResponse
	isSet bool
}

func (v NullableProfilesPatchProfileResponse) Get() *ProfilesPatchProfileResponse {
	return v.value
}

func (v *NullableProfilesPatchProfileResponse) Set(val *ProfilesPatchProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProfilesPatchProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProfilesPatchProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfilesPatchProfileResponse(val *ProfilesPatchProfileResponse) *NullableProfilesPatchProfileResponse {
	return &NullableProfilesPatchProfileResponse{value: val, isSet: true}
}

func (v NullableProfilesPatchProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfilesPatchProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


