/*
my-dev-cluster

Your custom SDK

API version: my-dev-cluster: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the AuthXboxLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthXboxLoginRequest{}

// AuthXboxLoginRequest struct for AuthXboxLoginRequest
type AuthXboxLoginRequest struct {
	// code generated on the client
	Code string `json:"code"`
	// Whether to create a user, if it does not exist
	CreateUser *bool `json:"create_user,omitempty"`
	// redirect url for client
	RedirectUrl string `json:"redirect_url"`
}

// NewAuthXboxLoginRequest instantiates a new AuthXboxLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthXboxLoginRequest(code string, redirectUrl string) *AuthXboxLoginRequest {
	this := AuthXboxLoginRequest{}
	this.Code = code
	this.RedirectUrl = redirectUrl
	return &this
}

// NewAuthXboxLoginRequestWithDefaults instantiates a new AuthXboxLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthXboxLoginRequestWithDefaults() *AuthXboxLoginRequest {
	this := AuthXboxLoginRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *AuthXboxLoginRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *AuthXboxLoginRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *AuthXboxLoginRequest) SetCode(v string) {
	o.Code = v
}

// GetCreateUser returns the CreateUser field value if set, zero value otherwise.
func (o *AuthXboxLoginRequest) GetCreateUser() bool {
	if o == nil || IsNil(o.CreateUser) {
		var ret bool
		return ret
	}
	return *o.CreateUser
}

// GetCreateUserOk returns a tuple with the CreateUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthXboxLoginRequest) GetCreateUserOk() (*bool, bool) {
	if o == nil || IsNil(o.CreateUser) {
		return nil, false
	}
	return o.CreateUser, true
}

// HasCreateUser returns a boolean if a field has been set.
func (o *AuthXboxLoginRequest) HasCreateUser() bool {
	if o != nil && !IsNil(o.CreateUser) {
		return true
	}

	return false
}

// SetCreateUser gets a reference to the given bool and assigns it to the CreateUser field.
func (o *AuthXboxLoginRequest) SetCreateUser(v bool) {
	o.CreateUser = &v
}

// GetRedirectUrl returns the RedirectUrl field value
func (o *AuthXboxLoginRequest) GetRedirectUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
func (o *AuthXboxLoginRequest) GetRedirectUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *AuthXboxLoginRequest) SetRedirectUrl(v string) {
	o.RedirectUrl = v
}

func (o AuthXboxLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthXboxLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.CreateUser) {
		toSerialize["create_user"] = o.CreateUser
	}
	toSerialize["redirect_url"] = o.RedirectUrl
	return toSerialize, nil
}

type NullableAuthXboxLoginRequest struct {
	value *AuthXboxLoginRequest
	isSet bool
}

func (v NullableAuthXboxLoginRequest) Get() *AuthXboxLoginRequest {
	return v.value
}

func (v *NullableAuthXboxLoginRequest) Set(val *AuthXboxLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthXboxLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthXboxLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthXboxLoginRequest(val *AuthXboxLoginRequest) *NullableAuthXboxLoginRequest {
	return &NullableAuthXboxLoginRequest{value: val, isSet: true}
}

func (v NullableAuthXboxLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthXboxLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


