/*
juhi-dev

Your custom SDK

API version: juhi-dev: v4 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the AuthSteamLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthSteamLoginRequest{}

// AuthSteamLoginRequest struct for AuthSteamLoginRequest
type AuthSteamLoginRequest struct {
	// Whether to create a user, if it does not exist
	CreateUser *bool `json:"create_user,omitempty"`
	LoginMetadata *AuthLoginMetadata `json:"login_metadata,omitempty"`
	// Key value pairs of the openid parameters
	OpenidParameters map[string]string `json:"openid_parameters"`
}

// NewAuthSteamLoginRequest instantiates a new AuthSteamLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthSteamLoginRequest(openidParameters map[string]string) *AuthSteamLoginRequest {
	this := AuthSteamLoginRequest{}
	this.OpenidParameters = openidParameters
	return &this
}

// NewAuthSteamLoginRequestWithDefaults instantiates a new AuthSteamLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthSteamLoginRequestWithDefaults() *AuthSteamLoginRequest {
	this := AuthSteamLoginRequest{}
	return &this
}

// GetCreateUser returns the CreateUser field value if set, zero value otherwise.
func (o *AuthSteamLoginRequest) GetCreateUser() bool {
	if o == nil || IsNil(o.CreateUser) {
		var ret bool
		return ret
	}
	return *o.CreateUser
}

// GetCreateUserOk returns a tuple with the CreateUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthSteamLoginRequest) GetCreateUserOk() (*bool, bool) {
	if o == nil || IsNil(o.CreateUser) {
		return nil, false
	}
	return o.CreateUser, true
}

// HasCreateUser returns a boolean if a field has been set.
func (o *AuthSteamLoginRequest) HasCreateUser() bool {
	if o != nil && !IsNil(o.CreateUser) {
		return true
	}

	return false
}

// SetCreateUser gets a reference to the given bool and assigns it to the CreateUser field.
func (o *AuthSteamLoginRequest) SetCreateUser(v bool) {
	o.CreateUser = &v
}

// GetLoginMetadata returns the LoginMetadata field value if set, zero value otherwise.
func (o *AuthSteamLoginRequest) GetLoginMetadata() AuthLoginMetadata {
	if o == nil || IsNil(o.LoginMetadata) {
		var ret AuthLoginMetadata
		return ret
	}
	return *o.LoginMetadata
}

// GetLoginMetadataOk returns a tuple with the LoginMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthSteamLoginRequest) GetLoginMetadataOk() (*AuthLoginMetadata, bool) {
	if o == nil || IsNil(o.LoginMetadata) {
		return nil, false
	}
	return o.LoginMetadata, true
}

// HasLoginMetadata returns a boolean if a field has been set.
func (o *AuthSteamLoginRequest) HasLoginMetadata() bool {
	if o != nil && !IsNil(o.LoginMetadata) {
		return true
	}

	return false
}

// SetLoginMetadata gets a reference to the given AuthLoginMetadata and assigns it to the LoginMetadata field.
func (o *AuthSteamLoginRequest) SetLoginMetadata(v AuthLoginMetadata) {
	o.LoginMetadata = &v
}

// GetOpenidParameters returns the OpenidParameters field value
func (o *AuthSteamLoginRequest) GetOpenidParameters() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.OpenidParameters
}

// GetOpenidParametersOk returns a tuple with the OpenidParameters field value
// and a boolean to check if the value has been set.
func (o *AuthSteamLoginRequest) GetOpenidParametersOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpenidParameters, true
}

// SetOpenidParameters sets field value
func (o *AuthSteamLoginRequest) SetOpenidParameters(v map[string]string) {
	o.OpenidParameters = v
}

func (o AuthSteamLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthSteamLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateUser) {
		toSerialize["create_user"] = o.CreateUser
	}
	if !IsNil(o.LoginMetadata) {
		toSerialize["login_metadata"] = o.LoginMetadata
	}
	toSerialize["openid_parameters"] = o.OpenidParameters
	return toSerialize, nil
}

type NullableAuthSteamLoginRequest struct {
	value *AuthSteamLoginRequest
	isSet bool
}

func (v NullableAuthSteamLoginRequest) Get() *AuthSteamLoginRequest {
	return v.value
}

func (v *NullableAuthSteamLoginRequest) Set(val *AuthSteamLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthSteamLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthSteamLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthSteamLoginRequest(val *AuthSteamLoginRequest) *NullableAuthSteamLoginRequest {
	return &NullableAuthSteamLoginRequest{value: val, isSet: true}
}

func (v NullableAuthSteamLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthSteamLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


