/*
my-dev-cluster

Your custom SDK

API version: my-dev-cluster: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the AuthGetUserIdsByLoginIdsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthGetUserIdsByLoginIdsResponse{}

// AuthGetUserIdsByLoginIdsResponse struct for AuthGetUserIdsByLoginIdsResponse
type AuthGetUserIdsByLoginIdsResponse struct {
	UserIds *map[string]string `json:"user_ids,omitempty"`
}

// NewAuthGetUserIdsByLoginIdsResponse instantiates a new AuthGetUserIdsByLoginIdsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthGetUserIdsByLoginIdsResponse() *AuthGetUserIdsByLoginIdsResponse {
	this := AuthGetUserIdsByLoginIdsResponse{}
	return &this
}

// NewAuthGetUserIdsByLoginIdsResponseWithDefaults instantiates a new AuthGetUserIdsByLoginIdsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthGetUserIdsByLoginIdsResponseWithDefaults() *AuthGetUserIdsByLoginIdsResponse {
	this := AuthGetUserIdsByLoginIdsResponse{}
	return &this
}

// GetUserIds returns the UserIds field value if set, zero value otherwise.
func (o *AuthGetUserIdsByLoginIdsResponse) GetUserIds() map[string]string {
	if o == nil || IsNil(o.UserIds) {
		var ret map[string]string
		return ret
	}
	return *o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthGetUserIdsByLoginIdsResponse) GetUserIdsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.UserIds) {
		return nil, false
	}
	return o.UserIds, true
}

// HasUserIds returns a boolean if a field has been set.
func (o *AuthGetUserIdsByLoginIdsResponse) HasUserIds() bool {
	if o != nil && !IsNil(o.UserIds) {
		return true
	}

	return false
}

// SetUserIds gets a reference to the given map[string]string and assigns it to the UserIds field.
func (o *AuthGetUserIdsByLoginIdsResponse) SetUserIds(v map[string]string) {
	o.UserIds = &v
}

func (o AuthGetUserIdsByLoginIdsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthGetUserIdsByLoginIdsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserIds) {
		toSerialize["user_ids"] = o.UserIds
	}
	return toSerialize, nil
}

type NullableAuthGetUserIdsByLoginIdsResponse struct {
	value *AuthGetUserIdsByLoginIdsResponse
	isSet bool
}

func (v NullableAuthGetUserIdsByLoginIdsResponse) Get() *AuthGetUserIdsByLoginIdsResponse {
	return v.value
}

func (v *NullableAuthGetUserIdsByLoginIdsResponse) Set(val *AuthGetUserIdsByLoginIdsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthGetUserIdsByLoginIdsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthGetUserIdsByLoginIdsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthGetUserIdsByLoginIdsResponse(val *AuthGetUserIdsByLoginIdsResponse) *NullableAuthGetUserIdsByLoginIdsResponse {
	return &NullableAuthGetUserIdsByLoginIdsResponse{value: val, isSet: true}
}

func (v NullableAuthGetUserIdsByLoginIdsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthGetUserIdsByLoginIdsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


