/*
my-dev-cluster

Your custom SDK

API version: my-dev-cluster: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the AuthEmailPasswordLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthEmailPasswordLoginRequest{}

// AuthEmailPasswordLoginRequest struct for AuthEmailPasswordLoginRequest
type AuthEmailPasswordLoginRequest struct {
	// Whether to create a user, if it does not exist
	CreateUser *bool `json:"create_user,omitempty"`
	// Email address used as login
	Email string `json:"email"`
	// Password used for login
	Password string `json:"password"`
}

// NewAuthEmailPasswordLoginRequest instantiates a new AuthEmailPasswordLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthEmailPasswordLoginRequest(email string, password string) *AuthEmailPasswordLoginRequest {
	this := AuthEmailPasswordLoginRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewAuthEmailPasswordLoginRequestWithDefaults instantiates a new AuthEmailPasswordLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthEmailPasswordLoginRequestWithDefaults() *AuthEmailPasswordLoginRequest {
	this := AuthEmailPasswordLoginRequest{}
	return &this
}

// GetCreateUser returns the CreateUser field value if set, zero value otherwise.
func (o *AuthEmailPasswordLoginRequest) GetCreateUser() bool {
	if o == nil || IsNil(o.CreateUser) {
		var ret bool
		return ret
	}
	return *o.CreateUser
}

// GetCreateUserOk returns a tuple with the CreateUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthEmailPasswordLoginRequest) GetCreateUserOk() (*bool, bool) {
	if o == nil || IsNil(o.CreateUser) {
		return nil, false
	}
	return o.CreateUser, true
}

// HasCreateUser returns a boolean if a field has been set.
func (o *AuthEmailPasswordLoginRequest) HasCreateUser() bool {
	if o != nil && !IsNil(o.CreateUser) {
		return true
	}

	return false
}

// SetCreateUser gets a reference to the given bool and assigns it to the CreateUser field.
func (o *AuthEmailPasswordLoginRequest) SetCreateUser(v bool) {
	o.CreateUser = &v
}

// GetEmail returns the Email field value
func (o *AuthEmailPasswordLoginRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AuthEmailPasswordLoginRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AuthEmailPasswordLoginRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *AuthEmailPasswordLoginRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthEmailPasswordLoginRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthEmailPasswordLoginRequest) SetPassword(v string) {
	o.Password = v
}

func (o AuthEmailPasswordLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthEmailPasswordLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateUser) {
		toSerialize["create_user"] = o.CreateUser
	}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

type NullableAuthEmailPasswordLoginRequest struct {
	value *AuthEmailPasswordLoginRequest
	isSet bool
}

func (v NullableAuthEmailPasswordLoginRequest) Get() *AuthEmailPasswordLoginRequest {
	return v.value
}

func (v *NullableAuthEmailPasswordLoginRequest) Set(val *AuthEmailPasswordLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthEmailPasswordLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthEmailPasswordLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthEmailPasswordLoginRequest(val *AuthEmailPasswordLoginRequest) *NullableAuthEmailPasswordLoginRequest {
	return &NullableAuthEmailPasswordLoginRequest{value: val, isSet: true}
}

func (v NullableAuthEmailPasswordLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthEmailPasswordLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


