/*
my-dev-cluster

Your custom SDK

API version: my-dev-cluster: v1 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapserInternal

import (
	"encoding/json"
)

// checks if the AuthVerifyEmailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthVerifyEmailResponse{}

// AuthVerifyEmailResponse struct for AuthVerifyEmailResponse
type AuthVerifyEmailResponse struct {
	User *AuthUser `json:"user,omitempty"`
}

// NewAuthVerifyEmailResponse instantiates a new AuthVerifyEmailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthVerifyEmailResponse() *AuthVerifyEmailResponse {
	this := AuthVerifyEmailResponse{}
	return &this
}

// NewAuthVerifyEmailResponseWithDefaults instantiates a new AuthVerifyEmailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthVerifyEmailResponseWithDefaults() *AuthVerifyEmailResponse {
	this := AuthVerifyEmailResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AuthVerifyEmailResponse) GetUser() AuthUser {
	if o == nil || IsNil(o.User) {
		var ret AuthUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthVerifyEmailResponse) GetUserOk() (*AuthUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AuthVerifyEmailResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given AuthUser and assigns it to the User field.
func (o *AuthVerifyEmailResponse) SetUser(v AuthUser) {
	o.User = &v
}

func (o AuthVerifyEmailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthVerifyEmailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableAuthVerifyEmailResponse struct {
	value *AuthVerifyEmailResponse
	isSet bool
}

func (v NullableAuthVerifyEmailResponse) Get() *AuthVerifyEmailResponse {
	return v.value
}

func (v *NullableAuthVerifyEmailResponse) Set(val *AuthVerifyEmailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthVerifyEmailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthVerifyEmailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthVerifyEmailResponse(val *AuthVerifyEmailResponse) *NullableAuthVerifyEmailResponse {
	return &NullableAuthVerifyEmailResponse{value: val, isSet: true}
}

func (v NullableAuthVerifyEmailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthVerifyEmailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


