# coding: utf-8

"""
    characters

    Your custom SDK

    The version of the OpenAPI document: characters: v3 SDK
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from snapser.models.storage_batch_single_increment_counter_response import StorageBatchSingleIncrementCounterResponse

class StorageBatchIncrementCounterResponse(BaseModel):
    """
    StorageBatchIncrementCounterResponse
    """
    counters: Optional[conlist(StorageBatchSingleIncrementCounterResponse)] = None
    __properties = ["counters"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StorageBatchIncrementCounterResponse:
        """Create an instance of StorageBatchIncrementCounterResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in counters (list)
        _items = []
        if self.counters:
            for _item in self.counters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['counters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StorageBatchIncrementCounterResponse:
        """Create an instance of StorageBatchIncrementCounterResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StorageBatchIncrementCounterResponse.parse_obj(obj)

        _obj = StorageBatchIncrementCounterResponse.parse_obj({
            "counters": [StorageBatchSingleIncrementCounterResponse.from_dict(_item) for _item in obj.get("counters")] if obj.get("counters") is not None else None
        })
        return _obj


