import express, { Application } from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import { RegisterRoutes } from './routes'; // This will be generated by TSOA
import { logger, requestIdMiddleware } from './logger';

export const app: Application = express();
app.use(cors());
app.use(bodyParser.json());
// Must run before the routes so every log line in a request carries its
// X-Request-Id. Snapser uses it to correlate logs across snaps.
app.use(requestIdMiddleware);

RegisterRoutes(app);

app.get('/healthz', (req, res) => { res.send('OK'); });

// Inbound Eventbus receiver.
//
// The Snapser Eventbus calls this endpoint to DELIVER events to this Snap. It
// is a RESERVED, root-level URL (like /healthz): no /v1 prefix and no
// byosnap id. It is intentionally a raw Express route (NOT a tsoa controller)
// so it stays OUT of the generated OpenAPI spec.
//
// express.json() (applied above via bodyParser.json()) populates req.body.
app.post('/internal/events', (req, res) => {
    logger.info('Received inbound eventbus event', { event: req.body });
    // TODO: Parse req.body and switch on the event subject to route each event
    //       to the appropriate handler in your business logic.
    res.sendStatus(200);
});

// Handle undefined routes
app.use((req, res) => {
    res.status(404).send({ message: 'Not Found' });
});
